# Generated by Django 2.0.6 on 2018-07-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(default=0, max_length=20)),
                ('style_name', models.CharField(default=0, max_length=20)),
                ('style_sam', models.IntegerField(default=0)),
                ('operators', models.IntegerField(default=0)),
                ('working', models.IntegerField(default=0)),
                ('production', models.IntegerField(default=0)),
                ('sam_earned', models.IntegerField(default=0)),
                ('sam_avaliable', models.IntegerField(default=0)),
                ('efficiency', models.IntegerField(default=0)),
                ('overtime', models.IntegerField(default=0)),
            ],
        ),
    ]
