# Generated by Django 2.0.6 on 2018-07-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ie',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ie',
            name='month',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='ie',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
