# Generated by Django 2.0.6 on 2018-09-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0003_auto_20180905_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_details', models.TextField()),
                ('price', models.IntegerField()),
                ('active', models.IntegerField(default='1')),
            ],
        ),
        migrations.DeleteModel(
            name='canteen',
        ),
    ]
