# Generated by Django 2.0.6 on 2018-09-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0004_auto_20180906_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sele', models.CharField(max_length=20)),
            ],
        ),
    ]
